-- 0010 - Booking display codes and public slot availability.
--
-- appointments.id remains the real UUID primary key. booking_code is a
-- patient-facing display code generated by the database so concurrent bookings
-- cannot pick the same value.

alter table public.appointments
  add column if not exists booking_code text;

create sequence if not exists public.appointment_booking_code_seq;

create or replace function public.generate_booking_code()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.booking_code is null or btrim(new.booking_code) = '' then
    new.booking_code :=
      'UR-' ||
      to_char(coalesce(new.created_at, now()) at time zone 'Asia/Baghdad', 'YYYYMMDD') ||
      '-' ||
      lpad(nextval('public.appointment_booking_code_seq')::text, 3, '0');
  end if;
  return new;
end;
$$;

drop trigger if exists trg_appointments_booking_code on public.appointments;
create trigger trg_appointments_booking_code
  before insert on public.appointments
  for each row execute function public.generate_booking_code();

with missing as (
  select id
  from public.appointments
  where booking_code is null or btrim(booking_code) = ''
  order by created_at, id
)
update public.appointments a
set booking_code =
  'UR-' ||
  to_char(coalesce(a.created_at, now()) at time zone 'Asia/Baghdad', 'YYYYMMDD') ||
  '-' ||
  lpad(nextval('public.appointment_booking_code_seq')::text, 3, '0')
from missing m
where a.id = m.id;

create unique index if not exists appointments_booking_code_uniq
  on public.appointments(booking_code)
  where booking_code is not null;

-- Cancelled/rejected bookings should not keep a slot blocked forever. Active
-- statuses remain protected by the database as the final race-condition guard.
drop index if exists public.appointments_doctor_slot_uniq;
create unique index if not exists appointments_doctor_active_slot_uniq
  on public.appointments(doctor_id, appointment_date, appointment_time)
  where status not in ('cancelled', 'rejected');

-- Availability RPC: exposes only occupied slots, not patient/appointment data.
create or replace function public.active_appointment_slots(
  p_doctor_id uuid,
  p_start date,
  p_end date
)
returns table (
  appointment_date date,
  appointment_time time
)
language sql
stable
security definer
set search_path = public
as $$
  select a.appointment_date, a.appointment_time
  from public.appointments a
  join public.doctors d on d.id = a.doctor_id
  where a.doctor_id = p_doctor_id
    and d.is_active = true
    and a.appointment_date between p_start and p_end
    and a.status not in ('cancelled', 'rejected')
  order by a.appointment_date, a.appointment_time;
$$;

grant execute on function public.active_appointment_slots(uuid, date, date) to authenticated;
